jobs:
- job: Create
  displayName: 'Setup Azure Application Environment'
  timeoutInMinutes: 720
  steps:
  - script: |
      set +e
      REPO="https://barings@dev.azure.com/Barings%20Standard%20IaC/Policy"
      git clone -b dev ${REPO}/_git/modules
      ls -la
    displayName: 'Checkout Barings Terraform Modules and CommonConfig'
    env:
      PAT: $(pat)

  - script: |
      az login --service-principal --username "$(ARM_CLIENT_ID)" --password "$(ARM_CLIENT_SECRET)" --tenant "$(ARM_TENANT_ID)"
      az account set -s "$(ARM_SUBSCRIPTION_ID)"
      terraform init
      terraform plan
      az logout
    displayName: 'tf'
    env: 
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
